spring:
  application:
    name: analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_analyzer
    username: postgres
    password: shareit
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

kafka:
  bootstrap-servers: localhost:9092

analyzer:
  kafka:
    consumer:
      hubs:
        group-id: analyzer-hub-events
      snapshots:
        group-id: analyzer-snapshot-events
      max-poll-records: 500
      session-timeout-ms: 10000
      heartbeat-interval-ms: 3000
      max-poll-interval-ms: 300000
    processor:
      poll-timeout: 1000
      auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 500
      session-timeout-ms: 10000
      heartbeat-interval-ms: 3000
      max-poll-interval-ms: 300000
      allow-auto-create-topics: false

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

logging:
  level:
    ru.yandex.practicum.telemetry.analyzer: WARN
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG